# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Simulation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Simulation.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10Simulation.proto\"\x94\x01\n\nSimulation\x12\x11\n\tnumACells\x18\x01 \x01(\x05\x12\x11\n\tnumBCells\x18\x02 \x01(\x05\x12\x0e\n\x06gammaA\x18\x03 \x01(\x01\x12\x0e\n\x06gammaB\x18\x04 \x01(\x01\x12\x0e\n\x06xValue\x18\x05 \x01(\x05\x12\x0e\n\x06yValue\x18\x06 \x01(\x05\x12\x0e\n\x06zValue\x18\x07 \x01(\x05\x12\x10\n\x08stopTime\x18\x08 \x01(\x05\"\x1e\n\x0bSimResponse\x12\x0f\n\x07message\x18\x01 \x01(\t29\n\tSimulator\x12,\n\rRunSimulation\x12\x0b.Simulation\x1a\x0c.SimResponse\"\x00\x62\x06proto3'
)




_SIMULATION = _descriptor.Descriptor(
  name='Simulation',
  full_name='Simulation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='numACells', full_name='Simulation.numACells', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='numBCells', full_name='Simulation.numBCells', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gammaA', full_name='Simulation.gammaA', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gammaB', full_name='Simulation.gammaB', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xValue', full_name='Simulation.xValue', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yValue', full_name='Simulation.yValue', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zValue', full_name='Simulation.zValue', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stopTime', full_name='Simulation.stopTime', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=169,
)


_SIMRESPONSE = _descriptor.Descriptor(
  name='SimResponse',
  full_name='SimResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='SimResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=201,
)

DESCRIPTOR.message_types_by_name['Simulation'] = _SIMULATION
DESCRIPTOR.message_types_by_name['SimResponse'] = _SIMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Simulation = _reflection.GeneratedProtocolMessageType('Simulation', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATION,
  '__module__' : 'Simulation_pb2'
  # @@protoc_insertion_point(class_scope:Simulation)
  })
_sym_db.RegisterMessage(Simulation)

SimResponse = _reflection.GeneratedProtocolMessageType('SimResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIMRESPONSE,
  '__module__' : 'Simulation_pb2'
  # @@protoc_insertion_point(class_scope:SimResponse)
  })
_sym_db.RegisterMessage(SimResponse)



_SIMULATOR = _descriptor.ServiceDescriptor(
  name='Simulator',
  full_name='Simulator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=203,
  serialized_end=260,
  methods=[
  _descriptor.MethodDescriptor(
    name='RunSimulation',
    full_name='Simulator.RunSimulation',
    index=0,
    containing_service=None,
    input_type=_SIMULATION,
    output_type=_SIMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMULATOR)

DESCRIPTOR.services_by_name['Simulator'] = _SIMULATOR

# @@protoc_insertion_point(module_scope)
