#!/bin/bash
#SBATCH -c32
#SBATCH -t24:00:00

# meta
VERSION=0.1

# functions
print()
{
  echo -e ${@}
}

start()
{
  print "\v"
  print "evomorph"
}

help()
{
  print
  print "usage"
  print "`tput bold`> evomorph [script]`tput sgr0`"
  print "  runs [script] with a Python interpreter that includes CompuCell3D"
  print
  print "`tput bold`> evomorph -v`tput sgr0`"
  print "  prints version info"
  print
  print "`tput bold`> evomorph`tput sgr0`"
  print "  prints this help message"
}

version()
{
  print "version ${VERSION}"
}

leave()
{
  print "\v"
  exit $1
}

# script
start

if [ $# == 0 ]; then
  help
  leave 0;
fi

if [ $1 == "-v" ]; then
  version
  leave 0;
fi

time singularity exec simbox.sif python3 $@
leave 0
