#!/bin/bash
#SBATCH -c16
#SBATCH -t12:00:00

# colors
NC='\033[0m'
BRED='\033[1;31m'
RED='\033[0;31m'
BGREEN='\033[1;32m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'

# meta
VERSION=0.1

# functions
print()
{
  echo -e ${@}
}

start()
{
  print "\v"
  print "${BRED}evo${BGREEN}morph${NC}"
}

help()
{
  print
  print "usage"
  print "`tput bold`> evomorph [script]`tput sgr0`"
  print "  runs [script] with a Python interpreter that includes CompuCell3D"
  print
  print "`tput bold`> evomorph -v`tput sgr0`"
  print "  prints version info"
  print
  print "`tput bold`> evomorph`tput sgr0`"
  print "  prints this help message"
}

version()
{
  print "version ${VERSION}"
}

leave()
{
  print "\v"
  exit $1
}

# script
start

if [ $# == 0 ]; then
  help
  leave 0;
fi

if [ $1 == "-v" ]; then
  version
  leave 0;
fi

singularity exec simbox.sif python3 $@
leave 0
